name: qobra-molecular-design
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.11.5
  # Core scientific computing
  - numpy=1.26.4
  - scipy=1.15.2
  - matplotlib=3.8.0
  - pandas=2.1.0
  
  # Quantum computing
  - pip
  - pip:
    - qiskit==1.4.2
    - qiskit-algorithms==0.3.1
    - qiskit-machine-learning==0.8.2
    - qiskit-ibm-runtime==0.37.0
  
  # Molecular sequence processing
  - biopython=1.85
  
  # Machine learning and optimization
  - scikit-learn=1.3.0
  - torch=2.2.0
  
  # Parallel processing
  - multiprocessing-logging
  
  # Data visualization and analysis
  - seaborn=0.12.0
  - plotly=5.17.0
  
  # Jupyter environment for interactive development
  - jupyter=1.0.0
  - jupyterlab=4.0.0
  - notebook=7.0.0
  - ipython=8.12.0
  - ipywidgets=8.1.0
  
  # Development tools
  - black=23.9.0
  - pytest=7.4.0
  
  # File I/O and utilities
  - pyyaml=6.0
  - h5py=3.9.0
  - pickle5=0.0.12
  
  # Optional: For enhanced molecular visualization
  - rdkit=2023.9.1  # For small molecule handling
  - mdanalysis=2.6.1  # For molecular dynamics analysis
  
  # Optional: For performance optimization
  - numba=0.58.0
  - cupy=12.3.0  # GPU acceleration (CUDA required)
